version: '3.5'

services:
  database:        
    image: mongo:latest
    container_name: rvp_database                
    volumes:
      - rvp_mongo-volume:/data      
    ports:
      - 27018:27017
    networks:
      - rvpnetwork
  backend:
    build: backend/
    image: backend-rvp:1.0
    container_name: rvp_backend
    volumes:
        - rvp_vue-volume:/build/uploaded
    ports:
      - 8081:8081
    depends_on:
      - database
    networks:
      - rvpnetwork
  frontend:
    build: frontend/
    image: frontend-rvp:1.0
    container_name: rvp-frontend
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - rvpnetwork

networks:
  rvpnetwork:
    name: rvpnetwork
    driver: bridge

volumes:
    rvp_vue-volume:
        external: false
    rvp_mongo-volume:
        external: false    


