version: '3.4'

services:
  backendts:
    image: backend-rvp
    network_mode: bridge
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8081:8081
